Http/routes.php
<?php
/**
 * Routes
 */

Route::group([
    'namespace' => 'Modules\Articles\Http\Controllers',
    'middleware' => 'web'
],
function () {
    Route::group([
        'prefix' => config('modules.configs.articles.route.prefix', 'articles')
    ],
    function () {
        Route::get('/', ['as' => 'articles.index', 'uses' => 'ArticlesController@index']);
        Route::get('/{slug}', ['as' => 'articles.show', 'uses' => 'ArticlesController@show']);
    });

    /**
     * Admin routes
     */
    Route::group([
        'as' => 'admin.articles.',
        'namespace' => 'Admin',
        'prefix' => config('modules.configs.articles.route.cp', 'articles'),
        'middleware' => config('admin.filter.auth')],
    function () {
        Route::get('/', ['as' => 'index', 'uses' => 'ArticlesController@index']);

        // Verbs
        Route::group([
            'prefix' => 'item'
        ],
        function () {
            Route::get('/create', ['as' => 'item.create', 'uses' => 'ArticlesController@create']);
            Route::get('/{article}/edit', ['as' => 'item.edit', 'uses' => 'ArticlesController@edit']);
            Route::post('/', ['as' => 'item.store', 'uses' => 'ArticlesController@store']);
            Route::put('/{article}', ['as' => 'item.update', 'uses' => 'ArticlesController@update']);
            Route::patch('/{article?}', ['as' => 'item.patch', 'uses' => 'ArticlesController@patch']);
            Route::delete('/{article?}', ['as' => 'item.destroy', 'uses' => 'ArticlesController@destroy']);
        });
    });
});

Resources/views/admin/create.blade.php
@extends('admin::layouts.master')
@section('title'){{ trans('articles::admin.form.create.header') }}@stop

@section('content')
    <div>
        @include('articles::admin.form', [
            'header' => trans('articles::admin.form.create.header')
        ])
    </div>
@stop

Resources/views/admin/edit.blade.php
@extends('admin::layouts.master')
@section('title'){{ trans('articles::admin.form.edit.header') }}@stop

@section('content')
    <div>
        @include('articles::admin.form', [
            'model' => $article, 
            'header' => trans('articles::admin.form.edit.header')
        ])
    </div>
@stop

Resources/views/admin/form.blade.php
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="active">
            <a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> {{ trans('admin.dashboard.header') }}</a>
        </li>
        <li>
            <a href="{{ route('admin.articles.index') }}">{{ trans('articles::admin.header') }}</a>
        </li>
        <li class="active">
            {{ $header }}
        </li>
    </ol>
@stop

<div class="row">
    @if(count($errors))
        <div class="col-lg-12">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-ban"></i></span></button>
                <span>Unable to save.</span>
            </div>
        </div>
    @endif

    @if(isset($model))
        {!! Form::model($model, [
            'class' => 'form-default', 
            'method' => 'PUT', 
            'files' => true, 
            'route' => [
                'admin.articles.item.update', $model->id
            ]
    ]) !!}
    @else
        {!! Form::open([
            'class' => 'form-default', 
            'files' => true, 
            'route' => 'admin.articles.item.store'
        ]) !!}
    @endif
    <div class="col-lg-12">
        <div class="header-group">
            <div>
                <h1 class="page-header">
                @if(isset($model))
                    @if($model->published == 2)
                        <span class="label label-primary header-label">Pending</span>
                    @elseif($model->published == 3)
                        <span class="label label-danger header-label">Expired</span>
                    @endif
                    {{ $model->title }}
                @else
                    {{ trans('articles::admin.form.create.alias') }}
                @endif
                </h1>
            </div>
            <div class="pull-right">
                <div class="btn-group">
                    <button class="btn btn-success">{{ trans('articles::admin.form.button.save') }}</button>
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li><a role="form-submit link" data-next="self">{{ trans('articles::admin.form.button.save_and_edit') }}</a></li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{!! route('admin.articles.index') !!}">
                                @if(isset($model))
                                    {{ trans('articles::admin.form.button.close') }}
                                @else
                                    {{ trans('articles::admin.form.button.cancel') }}
                                @endif
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-8">
        <div class="module tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#content" aria-controls="content" role="tab" data-toggle="tab">Content</a></li>
            </ul>

            <div class="tab-content">
                <!-- Content //-->
                <div role="tabpanel" class="tab-pane active" id="content">
                    <div class="section">
                        <div class="form-group">
                            {!! Form::label('title', trans('articles::admin.form.label.title')) !!}
                            {!! Form::text('title', null, ['class' => 'form-control']) !!}
                            {!! $errors->first('title', '<ul class="text-danger"><li>:message</li></ul>') !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('description', trans('articles::admin.form.label.description')) !!}
                            {!! Form::textarea('description', null, ['class' => 'form-control', 'role' => 'wysiwyg']) !!}
                            {!! $errors->first('description', '<ul class="text-danger"><li>:message</li></ul>') !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="module">
            @if(isset($model))
                <div class="section">
                    <div class="form-group">
                        <div class="btn-group stretch">
                            <a role="button" class="btn btn-default" disabled>
                                <i class="glyphicon glyphicon-eye-open"></i>
                                {{ trans('articles::admin.form.label.preview') }}
                            </a>
                            <a role="button" class="btn btn-default" href="{{ route('articles.show', $model->slug) }}" target="_blank">
                                <i class="glyphicon glyphicon-share-alt"></i>
                            </a>
                        </div>
                    </div>
                </div>
            @endif

            <div class="section">
                <div class="form-group">
                    {!! Form::label('slug', trans('articles::admin.form.label.slug')) !!}
                    {!! Form::text('slug', null, ['class' => 'form-control']) !!}
                    {!! $errors->first('slug', '<ul class="text-danger"><li>:message</li></ul>') !!}
                </div>

                <div class="form-group">
                    {!! Form::label('publish_up', 'Post Date') !!}
                    <div id="dtpicker.1" class="input-group" role="datepicker" data-role-link="dtpicker.2" data-role-type="min">
                        {!! Form::text('publishing[publish_up]', null, ['class' => 'form-control']) !!}
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('publish_down', 'Expiry Date') !!}
                    <div id="dtpicker.2" class="input-group" role="datepicker" data-role-link="dtpicker.1" data-role-type="max">
                        {!! Form::text('publishing[publish_down]', null, ['class' => 'form-control']) !!}
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>

                @if(isset($model))
                    <div class="form-group">
                        <label>{{ trans('articles::admin.form.label.created_at') }}</label>
                        <br />
                        <div role="date-display" data-value="{{ $model->created_at }}">{{ $model->created_at }}</div>
                    </div>
                @endif

                @if(isset($model->modified_by) and isset($model->modified_by_name))
                    <div class="form-group">
                        <label>{{ trans('articles::admin.form.label.modified_by') }}</label>
                        <br />
                        <a href="#" class="btn btn-simple">
                            <i class=" glyphicon glyphicon-user" aria-hidden="true"></i> {{ $model->modified_by_name }}
                        </a>
                        @if($model->modified_by == auth()->user()->id)
                            {{ trans('articles::admin.form.label.current_user') }}
                        @endif
                    </div>
                @endif
            </div>

            <div class="section">
                <div class="form-group">
                    {!! Form::label('publishing_access', trans('articles::admin.form.label.access')) !!}
                    <div class="switch mini auto">
                        {!! Form::checkbox('publishing[access]', 1,null, ['class' => 'form-control', 'id' => 'publishing_access']) !!}
                        {!! Form::label('publishing_access') !!}
                        <i class="active">Only logged in users can access</i>
                    </div>
                </div>

                <div class="form-group">
                    {!! Form::label('published', trans('articles::admin.form.label.published')) !!}
                    <div class="switch mini auto">
                        {!! Form::checkbox('published', 1,null, ['class' => 'form-control', 'id' => 'published']) !!}
                        {!! Form::label('published') !!}
                        <i class="active">Enabled</i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}
</div>


@push('jquery-scripts')
    $('form').on('submit', function() {
        App.set('page_exit_confirmation', false);
        return true;
    });
    $('input,select').on('change', function() {
        App.set('page_exit_confirmation', true);
    });
@endpush

Resources/views/admin/index.blade.php
@extends('admin::layouts.master')
@section('title'){{ trans('articles::admin.header') }}@stop

@section('breadcrumb')
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"><i class="fa fa-dashboard"></i> {{ trans('admin.menu.dashboard') }}</a>
        </li>
        <li class="active">
            {{ trans('articles::admin.header') }}
        </li>
    </ol>
@stop

@push('header')
    <script src="{{ asset( theme('admin.assets', 'js/bootstrap-group-select/bootstrap-group-select.min.js') ) }}"></script>
@endpush

@section('content')
    <div class="header-group">
        <div>
            <h1 class="page-header">
                {{ trans('articles::admin.header') }}
            </h1>
        </div>
        <div class="pull-right">
            <a href="{{ route('admin.articles.item.create') }}" class="btn btn-success">
                <i class="glyphicon glyphicon-plus"></i>
                Create new article...
            </a>
        </div>
    </div>


    <div id="content-wrapper" class="list-container module section">
        <div id="toolbar">
            <div class="btn-group">
                <div id="list:type"
                    data-id="visibility"
                    data-toggle="group-select"
                    data-type="dropdown"
                    data-allow-cookie="true"
                    data-bt-role="filters"
                    data-primary-class="btn btn-default">

                    <ul role="group-select-data" class="dropdown-menu">
                        <li class="active">Display All</li>
                        <li role="separator"></li>
                        <li data-filters-published="1"><i class="bullet-status status-success"></i> {{ trans('articles::admin.list.dropdown.live') }}</li>
                        <li data-filters-published="2"><i class="bullet-status status-primary"></i> {{ trans('articles::admin.list.dropdown.pending') }}</li>
                        <li data-filters-published="3"><i class="bullet-status status-danger"></i> {{ trans('articles::admin.list.dropdown.expired') }}</li>
                        <li role="separator"></li>
                        <li data-filters-published="0"><i class="bullet-status"></i> {{ trans('articles::admin.list.dropdown.disabled') }}</li>
                        <li role="separator"></li>
                        <li data-filters-deleted_only="1"><i class="bullet-status status-inactive"></i> {{ trans('articles::admin.list.dropdown.deleted') }}</li>
                    </ul>
                </div>

                <div class="btn-group">
                    <button type="button" 
                        class="btn btn-default dropdown-toggle" 
                        data-toggle="dropdown" 
                        aria-haspopup="true" 
                        aria-expanded="false"
                        data-bt-role="toggle"
                        disabled>
                        <i class="fa-fw glyphicon glyphicon-cog"></i><span class="caret"></span>
                    </button>

                    <ul class="dropdown-menu" data-toggle="group-select-link" data-link="visibility">
                        <li data-value="display all|live|pending|expired|un-published"><a href="#"
                            data-bt-action="remove"
                            data-url="{!! route('admin.articles.item.destroy') !!}"
                            data-method="DELETE">
                            {{ trans('articles::admin.list.dropdown.delete_all') }}</a></li>
                        <li data-value="display all|live|pending|expired|un-published" 
                            role="separator" class="divider"></li>
                        <li data-value="display all|live|pending|expired|un-published"><a href="#"
                            role="ajax bt-action" 
                            data-url="{!! route('admin.articles.item.patch', csrf_token()) !!}"
                            data-params-published="1"
                            data-method="PATCH">
                            Set Active</a></li>
                        <li data-value="display all|live|pending|expired|un-published"><a href="#"
                            role="ajax bt-action" 
                            data-url="{!! route('admin.articles.item.patch') !!}"
                            data-params-published="0"
                            data-method="PATCH">
                            Un-publish</a></li>

                        <li data-value="deleted">
                            <a href="#"
                                role="ajax bt-action" 
                                data-url="{!! route('admin.articles.item.patch') !!}"
                                data-params-restore="1"
                                data-method="PATCH">
                                {{ trans('articles::admin.list.dropdown.restore') }}</a>
                        </li>
                        <li data-value="deleted" role="separator" class="divider"></li>
                        <li data-value="deleted">
                            <a href="#"
                                role="confirm bt-action"
                                data-params-force_delete="1"
                                data-title="{{ trans('articles::admin.confirm.force_delete.title') }}" 
                                data-message="{{ trans('articles::admin.confirm.force_delete.message') }}"
                                data-url="{!! route('admin.articles.item.destroy') !!}"
                                data-method="DELETE">
                                {{ trans('articles::admin.list.dropdown.purge') }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <table id="table-articles"
                class="table table-no-bordered break-word extended"
                
                data-sort-order="desc"
                data-url="{!! route('admin.articles.index') !!}"
                data-data-field="data"
                data-side-pagination="server"
                data-pagination="true"
                data-columns-hidden="['publish_up', 'publish_down']"
                data-page-list="[10, 20, 50, 100]"

                data-toolbar="#toolbar">
            <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="title" data-sortable="true" data-switchable="false" data-uri="/admin/articles/item/{id}/edit" data-formatter="Formatter.title">
                    {{ trans('articles::admin.list.header.title') }}
                </th>
                <th data-field="slug" data-visible="false" data-formatter="Formatter.slug" data-sortable="true">
                    {{ trans('articles::admin.list.header.slug') }}
                </th>
                <th data-field="created_at" data-align="center" data-visible="false" data-formatter="Formatter.date" data-sortable="true">
                    {{ trans('articles::admin.list.header.created_at') }}
                </th>
                <th data-field="publish_up" data-align="center" data-formatter="Formatter.date" data-sortable="true">
                    {{ trans('articles::admin.list.header.post_date') }}
                </th>
                <th data-field="publish_down" data-align="center" data-formatter="Formatter.date" data-sortable="true">
                    {{ trans('articles::admin.list.header.expiry_date') }}
                </th>
                <th data-field="domain" data-visible="false" data-switchable="false" data-sortable="true">
                    {{ trans('articles::admin.list.header.domain') }}
                </th>
                <th data-field="published" data-align="center" data-card-view-only="true" data-formatter="Formatter.get_status">
                    {{ trans('articles::admin.list.header.published') }}
                </th>
            </tr>
            </thead>
        </table>
    </div>

    <script>
    var Formatter = Formatter || {
        // title
        title: function(value, row) {
            var statuses = {
                    1: 'success',
                    2: 'primary',
                    3: 'danger'
                },
                text = BT.formatter.linkable(value, row, this.uri);

            var status_type = statuses[row.published || 0];
            if (row.deleted_at) {
                status_type = 'inactive';
                text = '<a class="link" role="link" data-toggle="popover" data-trigger="click">{value}</a>'.replace(/{value}/, value);
            }

            if (status_type != undefined) 
                text = ['<span class="bullet-status status-{type}"></span>'
                    .replace(/{type}/, status_type), text].join('');

            return text;
        },
        // slug
        slug: function(value, row) {
            if (row.published == 1) 
                return '<a class="link" href="/articles/{slug}" target="_blank">{slug} <i class="glyphicon glyphicon-share-alt"></i></a>'
                    .replace(/{slug}/g, value);

            return value;
        },
        // format publishing
        get_status: function(value, row) {
            var statuses = {
                0: {
                    class: 'inactive',
                    label: '{{ trans('articles::admin.list.status.disabled') }}'
                },
                1: {
                    class: 'success',
                    label: '{{ trans('articles::admin.list.status.live') }}'
                },
                2: {
                    class: 'primary',
                    label: '{{ trans('articles::admin.list.status.pending') }}'
                },
                3: {
                    class: 'danger',
                    label: '{{ trans('articles::admin.list.status.expired') }}'
                },
            };

            var status = statuses[value];
            if (status == undefined) return '?';

            return '<span class="label label-{type}">{title}</span>'
                .replace(/{type}/, status.class)
                .replace(/{title}/, status.label);
        },
        date: function(value, row) {
            var d = moment(value),
                now = new Date(),
                is_today = d.isSame(now, "day");

            if (d.isValid() === false) return '';
            switch (this.field) {
                case 'publish_down':
                    return is_today ? d.fromNow() : d.format('D/M/YYYY');
                default:
                    return is_today ? d.calendar(now) : d.fromNow();
            }
        },
    };
    </script>
@stop

@push('jquery-scripts')
    // load bootstrap table
    BT.init('#table-articles', {
        notification: {
            target: $('#content-wrapper')
        }
    }, function(table) {
        // add popover render callback
        BT.field_callbacks.add('title', 'popover', function(row) {
            var tmpl = '<span class="popup-view" data-pos="relative"><p style="color:red;">This item has been marked as deleted. To <strong>undelete</strong> this record, click the <strong>Restore</strong> button.</p><i>Deleted At:</i><b>{deleted_at}</b><button class="edit btn btn-sm btn-primary" role="ajax" data-url="/admin/modules/articles/item/{id}" data-params-restore="1" data-method="PATCH">Restore</button>&nbsp;<button role="confirm" data-url="/admin/modules/articles/item/{id}" data-title="{{ trans('articles::admin.confirm.force_delete.title') }}" data-method="DELETE" data-message="{{ trans('articles::admin.confirm.force_delete.message') }}" data-params-force_delete="1" class="btn btn-sm btn-default">Remove Permanently</button></a></span>';
            // parse
            for (var k in row) tmpl = tmpl.replace(new RegExp('{'+k+'}', 'g'), row[k]);
            return tmpl;
        });

        //
        // event listener
        //
        $('#content-wrapper')
            // popover
            .on('click', '.popover button, [role*="bt-action"]', function() {
                var el = $(this);
                $('.alert').remove(), $('.popover').popover('hide');

                // events
                el.off('railed.beforeSend railed.onError railed.onComplete')
                .on('railed.beforeSend', function(r,s) {
                    Preloader.create('.list-container', 'centered', false,true);
                })
                .on('railed.onComplete', function(e, result) {
                    Preloader.clear(function() {
                        // check response
                        var success = result.success || result.status,
                            message = result.statusText || (result.message || 'No message returned.');

                        BT.notify(message, BT.options.notification.target, success===true?'info':'warning', 'insertBefore', success===true);
                        BT.call_method('refresh');
                    });
                });
            });

        // update data pagination
        this.option('sidePagination', 'server');
    });

    // list option
    $('[id="list:type"]')
        .on('select.bs.group-select', function(e, value) {
            var gs = $(this).data('bs.groupSelect'),
                filters = gs.options.filters || {};

            // update data
            var filter = $.extend(filters[value], {
                page: 1 // reset
            });
            $(this).data('filters', filter);

            BT.call_method('refresh', {query: filter});
        });
@endpush